
spawn_data = {1:
                  [{0: [{'seeker': 0}]}],

              2: [{0: [{'seeker': 1, 'twirler': 1, 'bouncer': 1}],
                    2: [{'seeker': 2, 'twirler': 1, 'bouncer': 1}],
                    4: [{'seeker': 2, 'twirler': 2, 'bouncer': 1}],
                    8: [{'seeker': 2, 'twirler': 1, 'bouncer': 2}],
                    10: [{'seeker': 2, 'twirler': 3, 'bouncer': 3}],
                    15: [{'seeker': 2, 'twirler': 1, 'bouncer': 2}],
                    17: [{'seeker': 3, 'twirler': 2, 'bouncer': 1}],
                    19: [{'bouncer': 6}]}],


              3: [{0: [{'seeker': 2}],
                    1: [{'seeker': 1}],
                    2: [{'seeker': 1}],
                    3: [{'seeker': 1}],
                    4: [{'seeker': 1}],
                    5: [{'seeker': 2}],
                    6: [{'seeker': 2}],
                    7: [{'seeker': 2}],
                   8: [{'seeker': 2}],
                   10: [{'seeker': 2}],
                   13: [{'seeker': 5}]
                   }],

              4: [{0: [{'bouncer': 2}],
                   2: [{'bouncer': 2}],
                   4: [{'bouncer': 2}],
                   6: [{'bouncer': 3}],
                   8: [{'wedge': 4}],
                   12: [{'wedge': 2}],
                   13: [{'wedge': 4}],
                   14: [{'wedge': 2}],
                   17: [{'wedge': 3}],
                   19: [{'wedge': 2}],
                   21: [{'wedge': 3}],
                   23: [{'wedge': 3}],
                   24: [{'wedge': 4}],
                   25: [{'wedge': 5}],
                   26: [{'wedge': 5}],
                   27: [{'wedge': 6}]}],

              5: [{0: [{'bouncer': 3}],
                   2: [{'bouncer': 3}],
                   3: [{'bouncer': 3}],
                   4: [{'bouncer': 3}],
                   5: [{'bouncer': 1}],
                   6: [{'bouncer': 5}],
                   8: [{'wedge': 6}],
                   12: [{'wedge': 6}],
                   13: [{'wedge': 6,'bouncer': 6}],
                   14: [{'wedge': 6,'bouncer': 6}],
                   17: [{'wedge': 6,'bouncer': 4}],
                   22: [{'wedge': 8,'bouncer': 5}],
                   26: [{'wedge': 10}]}],

              # do this manually in the custom level function to create lots of wedges and bouncers
              6: [{0: [{'palm': 3}],
                    2: [{'palm': 7,'wedge': 7}],
                    4: [{'palm': 7}],
                    6: [{'palm': 7,'wedge': 6}],
                    8: [{'wedge': 5}],
                    12: [{'palm': 3,'wedge': 8}],
                    13: [{'palm': 2,'wedge': 8}],
                    14: [{'palm': 7,'wedge': 8}],
                    15: [{'palm': 4,'wedge': 8}],
                    16: [{'palm': 7,'wedge': 8}],
                    17: [{'wedge': 12}],
                    18: [{'palm': 7,'wedge': 2}],
                    19: [{'wedge': 10}],
                    22: [{'wedge': 10}],
                    26: [{'wedge': 8}]}],

              7: [{0: [{'seeker': 1}],
                   1: [{'seeker': 1}],
                   3: [{'seeker': 1}],
                   5: [{'seeker': 1}],
                   7: [{'seeker': 1}],
                   10: [{'seeker': 2}],
                   13: [{'seeker': 5}]
                   }],

              8: [{0: [{'seeker': 1, 'twirler': 1, 'bouncer': 1, 'palm': 1, 'wedge': 1}],
                    2: [{'seeker': 1, 'twirler': 1, 'bouncer': 1, 'palm': 1, 'wedge': 1}],
                    6: [{'seeker': 2, 'twirler': 2, 'bouncer': 2, 'palm': 2, 'wedge': 2}],
                   11: [{'seeker': 2, 'twirler': 3, 'bouncer': 3, 'palm': 3, 'wedge': 3}],
                    17: [{'seeker': 2, 'twirler': 4, 'bouncer': 3, 'palm': 3, 'wedge': 5}],
                    20: [{'seeker': 2, 'twirler': 4, 'bouncer': 3, 'palm': 3, 'wedge': 5}],
                    24: [{'seeker': 2, 'twirler': 4, 'bouncer': 3, 'palm': 3, 'wedge': 5}],
                   }],

              9: [{0: [{'seeker': 4, 'twirler': 10}],
                   2: [{'seeker': 1, 'twirler': 1, 'bouncer': 3, 'palm': 1, 'wedge': 1}],
                   4: [{'bouncer': 4, 'palm': 5, 'wedge': 6}],
                   12: [{'seeker': 7}],
                   13: [{'bouncer': 8}],
                   14: [{'twirler': 5}],
                   16: [{'palm': 5, 'wedge': 5}],
                   17: [{'wedge': 10}],
                   18: [{'wedge': 10}],
                   19: [{'wedge': 10}],
                   20: [{'wedge': 10}],
                   21: [{'wedge': 10}],
                   22: [{'wedge': 10}],
                   22.5: [{'wedge': 10}],
                   23: [{'seeker': 3, 'twirler': 4, 'bouncer': 1, 'palm': 5, 'wedge': 5}],
                   24: [{'seeker': 3, 'twirler': 4, 'bouncer': 1, 'palm': 5, 'wedge': 5}],
                   25: [{'seeker': 3, 'twirler': 4, 'bouncer': 1, 'palm': 5, 'wedge': 5}],
                   35: [{'palm': 6}],
                   36: [{'palm': 6}],
                   37: [{'palm': 6}],
                   38: [{'palm': 6}],
                   39: [{'palm': 6}],
                   40: [{'twirler': 6}],
                   41: [{'twirler': 6}],
                   42: [{'twirler': 6}],
                   48: [{'wedge': 10}],
                   49: [{'wedge': 10}],
                   50: [{'wedge': 10}],
                   52: [{'bouncer': 5}],
                   53: [{'bouncer': 5}],
                   54: [{'bouncer': 5}],
                   57: [{'seeker': 5}],
                   58: [{'seeker': 5}],
                   59: [{'seeker': 3}],
                   60: [{'seeker': 3}],
                   61: [{'seeker': 3}],
                   62: [{'seeker': 3}],
                   63: [{'seeker': 3}],
                   64: [{'seeker': 3, 'bouncer': 3, 'palm': 3, 'wedge': 3}],
                   }],

                11: [{0: [{'twirler': 2}],
                    1: [{'seeker': 3}],
                    2: [{'bouncer': 2}],
                    5: [{'twirler': 3}],
                    6: [{'seeker': 3}],
                    7: [{'bouncer': 3}]},]
              }